jda:
  bot:
    startup-test: false
    version: '@project.version@'

spring:
  datasource:
    host: localhost
    url: jdbc:mysql://${spring.datasource.host}:3306/glacial_discord?useServerPrepStmts=false&rewriteBatchedStatements=true
    username: glacial
    password: glacial
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: INFO
